### ISSUE TITLE
Accurate measurement

### ISSUE THREAD

**Issue by fazekmar** [fazekmar/rmem#1]
Parse smaps if available.

**Comment by alicektx** [comment]
Hi. Stumbled upon such semi-accidentally (while digging something else into crates.io)...
Since it's inspired via ps_mem, you might also wanna have a look at [coremem](https://github.com/crquan/coremem).
Just thought i should mention / suggest such, say for possible inspiration
(ie. sorry for 'hijacking' the issue, if such is the case).

All the best

**Comment by fazekmar** [comment]
Initially I waited for the smaps support in the procfs crate and created this issue for that. After testing procfs it seems slow in my use case so I completely removed it.

As I see the coremem does almost the same thing I made (but I see other optimization possibilities from that code so thanks). Right now I think this is good enough and the ps_mem-like adjusting is unnecessary so I'm closing this.
